layout_spectrum: 0.8082438
typography_spectrum: 0.4731183
color:
  saturation: 1
  lightness: 0.5430108
  brandStrength: 0
  rhythmicContrast: 0.7401434
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
name: The Apprentice Raconteur
